- name: Install zsh
  become: true
  package:
    name: 
    - zsh
    state: present
- name: Get absolute path of zsh
  shell: command -v zsh
  register: zsh_path
  changed_when: false
- name: Ensure zsh path is in /etc/shells
  lineinfile:
    name: /etc/shells
    line: "{{ zsh_path.stdout }}"
    state: present
  check_mode: true
  register: presence
  failed_when: presence.changed
- name: zsh as default Shell
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ zsh_path.stdout }}"
- name: Install antibody
  aur:
    name:
    - antibody-bin
- name: Initialize antibody plugins
  shell:
    cmd: antibody bundle < zsh_plugins.txt > 020-antibody.zsh
    chdir: "{{ ansible_env.HOME }}/.dotfiles.d"
  changed_when: false
