---
  owner: TC
  magicsysrq: 1
  default_locale: en_SG.UTF-8
  numeric_locale: en_SG.UTF-8
  language_locales: en_SG:en
  time_locale: en_DK.UTF-8
  journald_config_directory: '/etc/systemd/journald.conf.d'
  resolved_config_directory: '/etc/systemd/resolved.conf.d'
  ssh_directory: '{{ ansible_env.HOME }}/.ssh'
  ntp_client_systemd_service: 'chronyd.service'
  ntp_sources: 
    nimt: ['time1.nimt.or.th', 'time2.nimt.or.th', 'time3.nimt.or.th', 'time4.nimt.or.th', 'time5.nimt.or.th']
    ntp_pool: ['th.pool.ntp.org']
