[linux.fonts.latin]
ui = "Roboto"
sans = "Roboto"
serif = "Roboto Serif"
monospace = "JetBrains Mono NL"
ui_monospace = "JetBrains Mono NL"
terminal_monospace = "Cascadia Mono"

[linux.fonts.thai]
sans = "Loma"
serif = "Noto Serif Thai"
monospace = "Tlwg Typo"