[linux.general]
locker = "gtklock -d"
terminal = "footclient"

[linux.fonts.latin]
ui = "Roboto"
sans = "Roboto"
serif = "Noto Serif"
monospace = "JetBrains Mono NL"
ui_monospace = "JetBrains Mono NL"
terminal_monospace = "Cascadia Mono PL"

[linux.fonts.thai]
sans = "Noto Sans Thai"
serif = "Noto Serif Thai"
monospace = "Tlwg Typo"