[linux.general]
launcher = "fuzzel"
locker = "gtklock -d"
terminal = "footclient"
powermenu = "nwg-bar -t ~/.config/nwg-bar/exit-bar/bar.json -s ~/.config/nwg-bar/exit-bar/style.css"

[linux.fonts.latin]
ui = "Roboto"
sans = "Roboto"
serif = "Noto Serif"
monospace = "JetBrains Mono NL"
ui_monospace = "JetBrains Mono NL"
terminal_monospace = "Cascadia Mono PL"

[linux.fonts.thai]
sans = "Loma"
serif = "Noto Serif Thai"
monospace = "Tlwg Typo"