[linux.general]
locker = "gtklock -d"

[linux.fonts.latin]
ui = "Lato"
sans = "Lato"
serif = "Noto Serif"
monospace = "JetBrains Mono NL"
ui_monospace = "JetBrains Mono NL"
terminal_monospace = "Cascadia Mono PL"

[linux.fonts.thai]
sans = "Loma"
serif = "Noto Serif Thai"
monospace = "Tlwg Typo"