[linux.fonts.latin]
ui = "Fira Sans"
sans = "Fira Sans"
serif = "Source Serif Pro"
monospace = "JetBrains Mono NL"
ui_monospace = "JetBrains Mono NL"
terminal_monospace = "Cascadia Mono"

[linux.fonts.thai]
sans = "Loma"
serif = "Kinnari"
monospace = "Tlwg Typo"