[linux.fonts.latin]
ui = "Inter"
sans = "Noto Sans Display"
serif = "Noto Serif"
monospace = "Hack"
ui_monospace = "Iosevka Fixed SS05 Extended"
terminal_monospace = "JetBrainsMono Nerd Font"

[linux.fonts.thai]
sans = "Loma"
serif = "Kinnari"
monospace = "Tlwg Typo"