[linux.fonts.latin]
ui = "Inter"
sans = "Noto Sans Display"
serif = "Noto Serif"
monospace = "JetBrains Mono NL"
ui_monospace = "JetBrains Mono NL"
terminal_monospace = "Cascadia Mono"

[linux.fonts.thai]
sans = "Loma"
serif = "Kinnari"
monospace = "Tlwg Typo"