---
- name: Install GUI-related components (pacman)
  become: true
  package:
    name:
      - ttf-jetbrains-mono
      - ttf-cascadia-code
      - ttf-liberation
      - ttf-ibm-plex
      - ttf-roboto
      - ttf-ubuntu-font-family
      - adobe-source-serif-fonts
      - ttf-fira-sans
      - ttf-fira-code
      - inter-font
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - gnome-keyring
      - nautilus
      - evince
      - firefox
      - chromium
      - mesa
      - libva-mesa-driver
      - libva-utils
      - vulkan-icd-loader
      - sway
      - swayidle
      - swaylock
      - waybar
      - mako
      - grim
      - slurp
      - wl-clipboard
      - xdg-desktop-portal-wlr
      - xdg-user-dirs
      - wofi
      - alacritty
      - tilix
      - xorg-xwayland
      - gammastep
      - kanshi
      - pipewire
      - pipewire-pulse
      - pavucontrol
      - pamixer
      - geany
      - code
      - libnotify
      - syncthing
      - keepassxc
      - papirus-icon-theme
      - arc-gtk-theme
      - qt5-wayland
      - qt5ct
      - qalculate-gtk
    state: present
- name: Install GUI-related components (AUR)
  kewlfft.aur.aur:
    name:
      - fonts-tlwg
      - nerd-fonts-jetbrains-mono
      - nerd-fonts-cascadia-code
      - ttf-roboto-serif 
      - brave-bin
      - vscodium-bin
      - greetd
      - greetd-gtkgreet
      - azote
      - nwg-look-bin
      - nwg-displays
      - nwg-drawer
      - nwg-bar-bin
      - swaync
    state: present

- name: Import PAM Tasks
  import_tasks: _pam.yml

- name: Import Login Manager Tasks
  import_tasks: _login_manager.yml
