---
- name: Install GUI-related components (pacman)
  become: true
  package:
    name:
    - ttf-hack
    - ttf-jetbrains-mono
    - ttf-cascadia-code
    - ttf-liberation
    - ttf-ubuntu-font-family
    - ttf-fira-code
    - inter-font
    - noto-fonts
    - noto-fonts-cjk
    - firefox
    - firefox-developer-edition
    - gnome-keyring
    - chromium
    - mesa
    - libva-mesa-driver
    - libva-utils
    - sway
    - swayidle
    - swaylock
    - waybar
    - mako
    - xdg-desktop-portal-wlr
    - wofi
    - alacritty
    - xorg-server-xwayland
    - pulseaudio
    - pavucontrol
    - geany
    - code
    - libnotify
    - syncthing
    - keepassxc
    - papirus-icon-theme
    - arc-gtk-theme
    state: present
- name: Install GUI-related components (AUR)
  aur:
    name:
    - nerd-fonts-hack
    - nerd-fonts-mononoki
    - nerd-fonts-jetbrains-mono
    state: present