---
- name: Install GUI-related components (pacman)
  become: true
  package:
    name:
      - ttf-jetbrains-mono
      - ttf-cascadia-code
      - ttf-liberation
      - ttf-ibm-plex
      - ttf-roboto
      - ttf-lato
      - ttf-ubuntu-font-family
      - adobe-source-serif-fonts
      - ttf-fira-sans
      - ttf-fira-code
      - inter-font
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - gnome-keyring
      - nautilus
      - evince
      - firefox
      - chromium
      - network-manager-applet
      - mesa
      - libva-mesa-driver
      - libva-utils
      - vulkan-icd-loader
      - sway
      - swaybg
      - swayidle
      - swaylock
      - waybar
      - mako
      - grim
      - slurp
      - wl-clipboard
      - xdg-desktop-portal-wlr
      - xdg-user-dirs
      - foot 
      - alacritty
      - tilix
      - xorg-xwayland
      - fuzzel
      - gammastep
      - kanshi
      - pipewire
      - pipewire-pulse
      - pipewire-jack
      - pavucontrol
      - pamixer
      - geany
      - code
      - libnotify
      - syncthing
      - keepassxc
      - papirus-icon-theme
      - arc-gtk-theme
      - qt5-wayland
      - qt5ct
      - kimageformats
      - qalculate-gtk
      - udisks2
      - udiskie
    state: present
- name: Install GUI-related components (AUR)
  kewlfft.aur.aur:
    name:
      - fonts-tlwg
      - nerd-fonts-jetbrains-mono
      - nerd-fonts-cascadia-code
      - ttf-roboto-serif 
      - brave-bin
      - vscodium-bin
      - greetd
      - greetd-gtkgreet
      - gtklock
      - azote
      - nwg-look-bin
      - nwg-displays
      - nwg-drawer-bin
      - nwg-bar-bin
      - swaync
      - qview
    state: present
- name: udisk Default Mount Options
  become: true
  community.general.ini_file:
    path: '{{ udisk_default_mount_path }}'
    mode: '0644'
    section: defaults
    option: "{{ item.key }}_defaults"
    value: "{{ item.value }}"
    no_extra_spaces: true
    state: present
  with_dict:
    ext4: "noatime,commit=30"
    btrfs: "noatime,compress=zstd:1"
    ntfs: "uid=$UID,gid=$GID,noatime,prealloc"

- name: Import PAM Tasks
  import_tasks: _pam.yml

- name: Import Login Manager Tasks
  import_tasks: _login_manager.yml
