---
- name: Install GUI-related components (pacman)
  become: true
  package:
    name:
    - ttf-hack
    - ttf-jetbrains-mono
    - ttf-cascadia-code
    - ttf-liberation
    - ttf-ibm-plex
    - ttf-ubuntu-font-family
    - adobe-source-serif-fonts
    - ttf-fira-sans
    - ttf-fira-code
    - inter-font
    - noto-fonts
    - noto-fonts-cjk
    - gnome-keyring
    - firefox
    - chromium
    - mesa
    - libva-mesa-driver
    - libva-utils
    - sway
    - swayidle
    - swaylock
    - waybar
    - mako
    - xdg-desktop-portal-wlr
    - wofi
    - alacritty
    - tilix
    - xorg-xwayland
    - gammastep
    - kanshi
    - pipewire
    - pipewire-pulse
    - pavucontrol
    - geany
    - code
    - libnotify
    - syncthing
    - keepassxc
    - papirus-icon-theme
    - arc-gtk-theme
    - qt5-wayland
    - qt5ct
    - gnome-keyring
    state: present
- name: Install GUI-related components (AUR)
  kewlfft.aur.aur:
    name:
    - fonts-tlwg
    - nerd-fonts-hack
    - nerd-fonts-jetbrains-mono
    - vscodium-bin
    - greetd
    - greetd-gtkgreet
    state: present
- name: Set GNOME Keyring at boot time of Console Login PAM (auth)
  become: true
  community.general.pamd:
    name: login
    type: auth
    control: include
    module_path: system-local-login
    new_type: auth
    new_control: optional
    new_module_path: pam_gnome_keyring.so
    state: after
- name: Set GNOME Keyring at boot time of Console Login PAM (session)
  become: true
  community.general.pamd:
    name: login
    type: session
    control: include
    module_path: system-local-login
    new_type: session
    new_control: optional
    new_module_path: pam_gnome_keyring.so
    module_arguments: auto_start
    state: after
- name: Set GNOME Keyring at boot time of greetd PAM (auth)
  become: true
  community.general.pamd:
    name: greetd
    type: auth
    control: include
    module_path: system-local-login
    new_type: auth
    new_control: optional
    new_module_path: pam_gnome_keyring.so
    state: after
- name: Set GNOME Keyring at boot time of greetd PAM (session)
  become: true
  community.general.pamd:
    name: greetd
    type: session
    control: include
    module_path: system-local-login
    new_type: session
    new_control: optional
    new_module_path: pam_gnome_keyring.so
    module_arguments: auto_start
    state: after
- name: Create {{ wayland_enablement_path }}
  become: true
  template:
    src: wayland-enablement.sh.j2
    dest: '{{ wayland_enablement_path }}'
- name: Create {{ load_systemd_envs_path }}
  become: true
  template:
    src: load-systemd-envs.sh.j2
    dest: '{{ load_systemd_envs_path }}'
- name: Create {{ sway_run_path }}
  become: true
  template:
    src: sway-run.sh.j2
    dest: '{{ sway_run_path }}'
    mode: 0755
- name: Create greetd Config file
  become: true
  template:
    src: greetd-config.toml.j2
    dest: '/etc/greetd/config.toml'
- name: Create greetd gtkgreet-sway Config file
  become: true
  template:
    src: greetd-gtkgreet-sway-config.j2
    dest: '{{ gtkgreet_sway_config }}'
- name: Create greetd Config file
  become: true
  template:
    src: greetd-config.toml.j2
    dest: '/etc/greetd/config.toml'
- name: Create greetd session file
  become: true
  template:
    src: greetd-environments.j2
    dest: '/etc/greetd/environments'
- name: Create Sway Custom Desktop Session
  become: true
  template:
    src: sway-custom-desktop-entry.j2
    dest: /usr/share/wayland-sessions/sway-custom.desktop