---
- name: Install GUI-related components (pacman)
  become: true
  package:
    name:
      - ttf-jetbrains-mono
      - ttf-cascadia-code
      - ttf-liberation
      - ttf-roboto
      - ttf-fira-sans
      - ttf-fira-code
      - ttf-ubuntu-font-family
      - ttf-ibm-plex
      - inter-font
      - adobe-source-serif-fonts
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - ttf-jetbrains-mono-nerd
      - ttf-cascadia-code-nerd
      - polkit-kde-agent 
      - pcmanfm-qt
      - atril
      - firefox
      - chromium
      - network-manager-applet
      - mesa
      - libva-mesa-driver
      - libva-utils
      - vulkan-icd-loader
      - vulkan-validation-layers
      - sway
      - swaybg
      - swayidle
      - swaylock
      - waybar
      - mako
      - grim
      - slurp
      - wl-clipboard
      - xdg-desktop-portal-wlr
      - xdg-user-dirs
      - foot 
      - alacritty
      - tilix
      - xorg-xwayland
      - fuzzel
      - gammastep
      - kanshi
      - pipewire
      - pipewire-pulse
      - pipewire-jack
      - pavucontrol
      - pamixer
      - geany
      - code
      - libnotify
      - syncthing
      - keepassxc
      - papirus-icon-theme
      - arc-gtk-theme
      - qt5-wayland
      - qt5ct
      - kvantum
      - lxqt-archiver
      - lximage-qt
      - qt5-imageformats
      - kimageformats
      - qalculate-gtk
      - udisks2
      - udiskie
    state: present
- name: Install GUI-related components (AUR)
  kewlfft.aur.aur:
    name:
      - fonts-tlwg
      - brave-bin
      - vscodium-bin
      - greetd
      - greetd-qtgreet
      - greetd-tuigreet
      - gtklock
      - azote
      - wlr-randr
      - nwg-look-bin
      - nwg-displays
      - nwg-bar-bin
      - swaync
    state: present
- name: udisks2 Mount Options
  become: true
  community.general.ini_file:
    path: '{{ udisk_mount_options_path }}'
    mode: '0644'
    section: defaults
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    no_extra_spaces: true
    state: present
  with_dict:
    ext4_allow: errors=remount-ro,commit
    ext4_defaults: "noatime,commit=30"
    btrfs_defaults: "noatime,compress=zstd:1"
    ntfs_defaults: "uid=$UID,gid=$GID,noatime,prealloc"
- name: gsettings for gnome and gtk settings
  shell: |
    gsettings set org.gnome.desktop.privacy recent-files-max-age 0
    gsettings set org.gnome.desktop.privacy remember-recent-files false
    gsettings set org.gtk.Settings.FileChooser startup-mode "cwd"

    gsettings set org.gnome.desktop.interface monospace-font-name "JetBrains Mono 11"
    gsettings set org.gnome.desktop.thumbnail-cache maximum-size 0
    gsettings set org.gnome.desktop.thumbnailers disable-all true

- name: Import PAM Tasks
  import_tasks: _pam.yml

- name: Import Login Manager Tasks
  import_tasks: _login_manager.yml
