---
- name: Install GUI-related components (pacman)
  become: true
  package:
    name:
    - ttf-hack
    - ttf-jetbrains-mono
    - ttf-cascadia-code
    - ttf-liberation
    - ttf-ubuntu-font-family
    - ttf-fira-code
    - inter-font
    - noto-fonts
    - noto-fonts-cjk
    - firefox
    - gnome-keyring
    - chromium
    - mesa
    - libva-mesa-driver
    - libva-utils
    - sway
    - swayidle
    - swaylock
    - waybar
    - mako
    - xdg-desktop-portal-wlr
    - wofi
    - alacritty
    - kitty
    - xorg-server-xwayland
    - gammastep
    - pulseaudio
    - pavucontrol
    - geany
    - code
    - libnotify
    - syncthing
    - keepassxc
    - papirus-icon-theme
    - arc-gtk-theme
    - qt5-wayland
    state: present
- name: Install GUI-related components (AUR)
  aur:
    name:
    - nerd-fonts-hack
    - nerd-fonts-jetbrains-mono
    - ant-dracula-gtk-theme
    state: present
- name: Set GNOME Keyring at boot time of Console Login PAM (auth)
  become: true
  community.general.pamd:
    name: login
    type: auth
    control: include
    module_path: system-local-login
    new_type: auth
    new_control: optional
    new_module_path: pam_gnome_keyring.so
    state: after
- name: Set GNOME Keyring at boot time of Console Login PAM (session)
  become: true
  community.general.pamd:
    name: login
    type: session
    control: include
    module_path: system-local-login
    new_type: session
    new_control: optional
    new_module_path: pam_gnome_keyring.so
    module_arguments: auto_start
    state: after