---
- name: Create {{ journald_config_directory }} directory if not exist
  become: true
  file:
    path: '{{ journald_config_directory }}'
    state: directory
    mode: 0755
- name: Create journald config file
  become: true
  template:
    src: 'journald.conf.j2'
    dest: '{{ journald_config_directory }}/99-custom-journald.conf'
    mode: 0644