---
# - name: Disable IPv6 due to timeout issue when connecting to IPv6-supported sites
#   become: true
#   lineinfile:
#     path: /etc/sysctl.d/40-ipv6.conf
#     line: "net.ipv6.conf.all.disable_ipv6 = 1"
#     state: present
- name: Prefer IPv4 over IPv6 in getaddrinfo config
  become: true
  lineinfile:
    path: /etc/gai.conf
    line: "precedence ::ffff:0:0/96  100"
    insertafter: EOF
    state: present
- name: Enable NetworkManager Service
  become: true
  systemd:
    name: NetworkManager
    state: started
    enabled: true
    masked: false
- name: Enable systemd-resolved Service
  become: true
  systemd:
    name: systemd-resolved
    state: started
    enabled: true
    masked: false
- name: systemd-resolved /etc/resolv.conf symlink
  become: true
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true