---
# - name: Disable IPv6 due to timeout issue when connecting to IPv6-supported sites
#   become: true
#   lineinfile:
#     path: /etc/sysctl.d/40-ipv6.conf
#     line: "net.ipv6.conf.all.disable_ipv6 = 1"
#     state: present
- name: Prefer IPv4 over IPv6 in getaddrinfo config
  become: true
  lineinfile:
    path: /etc/gai.conf
    line: "precedence ::ffff:0:0/96  100"
    insertafter: EOF
    state: present
- name: Enable NetworkManager Service
  become: true
  systemd:
    name: NetworkManager
    state: started
    enabled: true
    masked: false
- name: Enable systemd-resolved Service
  become: true
  systemd:
    name: systemd-resolved
    state: started
    enabled: true
    masked: false
- name: systemd-resolved /etc/resolv.conf symlink
  become: true
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: true
- name: Enable systemd-timesyncd.service
  become: true
  systemd:
    name: systemd-timesyncd.service
    state: started
    enabled: true
    masked: false
- name: Create {{ systemd_timesyncd_conf_location }} directory if it does not exist
  become: true
  file:
    path: '{{ systemd_timesyncd_conf_location }}'
    state: directory
    mode: '0755'
- name: Setup NTP Servers
  become: true
  template:
    src: 'systemd-timesyncd.conf.j2'
    dest: '{{ systemd_timesyncd_conf_location }}/00-system.conf'
  notify:
    - Restart systemd-timesyncd