---
- name: Get absolute path of zsh
  shell: command -v zsh
  register: zsh_path
  changed_when: false
- name: Ensure zsh path is in /etc/shells
  lineinfile:
    name: /etc/shells
    line: "{{ zsh_path.stdout }}"
    state: present
  check_mode: true
  register: presence
  failed_when: presence.changed
- name: zsh as Default Shell
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: "{{ zsh_path.stdout }}"