---
- name: Install necessities
  become: true
  package:
    name:
    - sudo
    - curl
    - wget
    - vim
    - ripgrep
    - neovim
    - base-devel
    - python
    - python-pip
    - python-psutil
    - man
    - htop
    - bashtop
    - openssh
    - networkmanager
    - iwd
    - ldns
    - zsh
    - lsd
    - java-runtime-common
    - java-environment-common
    - yarn
    - rustup
    - docker
    - docker-compose
    - tlp
    state: present
- name: Add groups to {{ ansible_user_id }}
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups:
    - "{{ superuser_group }}"
    - docker
    - video
    append: true
- name: Register {{ superuser_group }} group to sudoers.d
  become: true
  lineinfile:
    path: /etc/sudoers.d/00-{{ superuser_group }}-group
    line: "%{{ superuser_group }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    mode: 0440
    create: true
    validate: "visudo -cf %s"
- name: Include sudoers.d if not present
  become: true
  lineinfile:
    path: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "visudo -cf %s"
- name: Enable Magic SysRq = {{ magicsysrq }}
  become: true
  lineinfile:
    path: /etc/sysctl.d/magic-sysrq.conf
    line: "kernel.sysrq = {{ magicsysrq }}"
    state: present
- name: Install AUR Helper
  aur:
    name: yay-bin
    #skip_installed: true
- name: Install AUR Components
  aur:
    name:
    - fnm-bin
    - antibody-bin
    - nerd-fonts-hack
- name: Enable NetworkManager Service
  become: true
  systemd:
    name: NetworkManager
    enabled: true
    masked: false
- name: Enable fstrim Timer
  become: true
  systemd:
    name: fstrim.timer
    enabled: true
    masked: false
