---
- name: Install necessities
  become: true
  package:
    name:
    - sudo
    - curl
    - wget
    - vim
    - ripgrep
    - neovim
    - base-devel
    - python
    - python-pip
    - python-psutil
    - man
    - tmux
    - htop
    - bashtop
    - openssh
    - networkmanager
    - iwd
    - ldns
    - zsh
    - lsd
    - java-runtime-common
    - java-environment-common
    - yarn
    - rustup
    - docker
    - docker-compose
    - tlp
    - terminus-font
    - p7zip
    - unzip
    state: present
- name: Add groups to {{ ansible_user_id }}
  become: true
  user:
    name: "{{ ansible_user_id }}"
    groups:
    - "{{ superuser_group }}"
    - docker
    - video
    append: true
- name: Register {{ superuser_group }} group to sudoers.d
  become: true
  lineinfile:
    path: /etc/sudoers.d/00-{{ superuser_group }}-group
    line: "%{{ superuser_group }} ALL=(ALL) NOPASSWD: ALL"
    state: present
    mode: 0440
    create: true
    validate: "visudo -cf %s"
- name: Include sudoers.d if not present
  become: true
  lineinfile:
    path: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "visudo -cf %s"
- name: Enable Magic SysRq = {{ magicsysrq }}
  become: true
  lineinfile:
    path: /etc/sysctl.d/99-magic-sysrq.conf
    line: "kernel.sysrq = {{ magicsysrq }}"
    state: present
    create: true
# - name: Disable IPv6 due to timeout issue when connecting to IPv6-supported sites
#   become: true
#   lineinfile:
#     path: /etc/sysctl.d/40-ipv6.conf
#     line: "net.ipv6.conf.all.disable_ipv6 = 1"
#     state: present
- name: Prefer IPv4 over IPv6 in getaddrinfo config
  become: true
  lineinfile:
    path: /etc/gai.conf
    line: "precedence ::ffff:0:0/96  100"
    insertafter: EOF
    state: present
- name: Install AUR Helper
  aur:
    name: yay-bin
    state: present
    #skip_installed: true
- name: Install AUR Components
  aur:
    name:
    - fnm-bin
    - antibody-bin
    state: present
- name: Enable NetworkManager Service
  become: true
  systemd:
    name: NetworkManager
    enabled: true
    masked: false
- name: Enable fstrim Timer
  become: true
  systemd:
    name: fstrim.timer
    enabled: true
    masked: false
- name: Set Linux Console Default Bitmap font
  become: true
  lineinfile:
    path: /etc/vconsole.conf
    line: "FONT=ter-u28n"
    state: present
    create: true
- name: Set Default Locale to {{ default_locale }}
  become: true
  lineinfile:
    path: /etc/locale.conf
    line: "LANG={{ default_locale }}"
    state: present
    create: true
- name: Set LANGUAGE Locale to {{ language_locales }}
  become: true
  lineinfile:
    path: /etc/locale.conf
    line: "LANGUAGE={{ language_locales }}"
    state: present
    create: true
- name: Set Numeric Locale to {{ numeric_locale }}
  become: true
  lineinfile:
    path: /etc/locale.conf
    line: "LC_NUMERIC={{ numeric_locale }}"
    state: present
    create: true
