---
- name: Enable Pacman Parallel Download
  become: true
  lineinfile:
    path: /etc/pacman.conf
    regexp: "^#ParallelDownloads.*$"
    line: "ParallelDownloads = 5"
    state: present

- name: Install necessities
  become: true
  package:
    name:
      - sudo
      - opendoas
      - btrfs-progs
      - curl
      - curlie
      - wget
      - vim
      - ripgrep
      - neovim
      - base-devel
      - polkit
      - python
      - python-pip
      - python-psutil
      - man-db
      - tmux
      - htop
      - bashtop
      - openssh
      - zsh
      - lsd
      - jq
      - go-yq

      ## Modern Unix
      - bat
      - duf

      ## Network Tools
      - networkmanager
      - iwd
      - ldns
      - nmap
      - gping
      - dog
      - traceroute

      - java-runtime-common
      - java-environment-common
      - go
      - rustup
      - nodejs
      - yarn
      - docker
      - docker-compose
      - tlp
      - terminus-font
      - p7zip
      - unzip
      - acpi_call
      - lshw
    state: present

- name: Import Privileges Tasks
  import_tasks: _privileges.yml

- name: Import Network Tasks
  import_tasks: _network.yml

- name: Enable Magic SysRq = {{ magicsysrq }}
  become: true
  lineinfile:
    path: /etc/sysctl.d/99-magic-sysrq.conf
    line: "kernel.sysrq = {{ magicsysrq }}"
    state: present
    create: true
- name: Install AUR Helper
  kewlfft.aur.aur:
    name: yay-bin
    state: present
    #skip_installed: true
- name: Install AUR Components
  kewlfft.aur.aur:
    name:
      - fnm-bin
      - jdk11-temurin
    state: present
- name: Enable fstrim Timer
  become: true
  systemd:
    name: fstrim.timer
    enabled: true
    masked: false
- name: Set Linux Console Default Bitmap font
  become: true
  lineinfile:
    path: /etc/vconsole.conf
    line: "FONT=ter-u28n"
    state: present
    create: true
- name: Locale Setting
  become: true
  lineinfile:
    path: /etc/locale.conf
    regexp: "^#? *{{ item.key | regex_escape() }}="
    line: "{{ item.key }}={{ item.value }}"
    state: present
    create: true
  with_dict:
    "LANG": "{{ default_locale }}"
    "LANGUAGE": "{{ language_locales }}"
    "LC_NUMERIC": "{{ numeric_locale }}"

- name: Ensure Rustup Stable Toolchain is installed
  shell: rustup install stable

- name: Import Zsh Tasks
  import_tasks: _zsh.yml

- name: Import SSH Tasks
  import_tasks: _ssh.yml
