- name: Setup local workstation
  hosts: local
  vars_prompt:
    name: machine_type
    prompt: Machine Type (`personal` or `work`)
    default: "personal"
    private: false
  roles:
    - general
    - gui
